### ISSUE TITLE
Menu Companion has not worked for several months

### ISSUE THREAD

**Issue by Jefferderp** [dakhnod/Fossil-HR-Menu-Companion#10]
Hello!

I figured I'd open this issue as I've been unable to use the companion app for many months now.

One day it spontaneously stopped launching on my watch, when pressing any of the three buttons. I've checked, verified, redone and reinstalled everything under the sun, revisiting every few weeks, to no avail. Here's a non-exhaustive list of what I've tried/confirmed:

* Latest Gadgetbridge 0.79.1
* Latest version of this app
* Android 13 (Graphene OS)
* My menu in the companion app is valid (and I've never changed since it stopped working)
* My watch buttons are working, and can launch other watch apps
* I've ensured the watch face version is greater than 1.10 (in my case, 1.11).
* I've tried creating new watch faces.
* I made sure the watch face in the companion app has the same name as the watch face in Gadgetbridge.
* I've ensured my button bindings in Gadgetbridge are set to "Nothing" so there's no conflict.
* I've tried three different Fossil HR watches
* My watch has the Commute app installed
* I've tried with firmware versions 4.4 (old design), 5.0 (refresh) and the latest available from the Fossil app.
* I've read all the documentation on this feature thoroughly.
* The watch Companion app is able to send intents to Tasker, in case it's relevant.

As mentioned, this simply stopped working one day, possibly upon updating the Gadgetbridge app, though at this point I don't recall. Do you still use the menu companion, and does it work for you?

I'd greatly appreciate any insights you might have!

I'd be glad to provide any relevant logs. I've also attached my watch face and menu companion JSON in case those are helpful.

[jefferderp.zip](https://github.com/dakhnod/Fossil-HR-Menu-Companion/files/14465640/jefferderp.zip)

Thank you for this excellent app, and I hope to continue enjoying it soon.

**Comment by Jefferderp** [comment]
I would appreciate if anybody who sees this issue can weigh in. If the menu companion is working for you, what app/software versions are you running?

**Comment by dakhnod** [comment]
did you restart the watch?

**Comment by Jefferderp** [comment]
Restart it how? I'm only aware of resetting it (holding the crown button).

I've let it run down to 0% battery many times, to force a reboot, but it's never helped.

**Comment by dakhnod** [comment]
did you try uninstalling the timer app and reinstalling it?
Also, how did you configure the button?

**Comment by dakhnod** [comment]
Furthermote, did you try installing the stock stopwatchApp?

**Comment by Jefferderp** [comment]
I'm surprised to learn that these are relevant to the menu companion. I've just tried with the Timer app uninstalled and then reinstalled, re-pushing my watch face each time. No effect. Same with the stopwatch app, I tried with both Stock and BetterStopwatch installed.

Here's a screenshot of what my menu config looks like:

![Screenshot_20240301-154523](https://github.com/dakhnod/Fossil-HR-Menu-Companion/assets/13530594/743e05c2-b1f1-4bb6-9092-d78d968d62f4)

**Comment by dakhnod** [comment]
can you start the stopwatch from the watches menu? Like smi-long pressing the middle button?

**Comment by dakhnod** [comment]
Oh, your are talking about the mnu, not the stopwatch, my bad.

So, you cannot push any config via the companion?

**Comment by Jefferderp** [comment]
Yeah, my original message has all the details. The menu companion does not activate despite everything I've tried.

**Comment by dakhnod** [comment]
ah, got it, the menu doesn't show up. did you try with a smaller configuration?

**Comment by Jefferderp** [comment]
Yes, and I also tried with the default configuration.

Thanks for your help!

**Comment by dakhnod** [comment]
You really seem to be under some sort of curse, it seems...in any case, I am sure we can figure this out. Are you able to check if GB sends any data to the watch when you upload the configuration? Also, can you send me the watchface .wapp file you generated?

I am unsure where to find it right now, but there is a limit to the JSON size that you can dynamically upload through GB.
Thus, GB remembers the json, and bakes it into the watchface when you reinstall it. And I would be curious to inspect said watchface.

**Comment by Jefferderp** [comment]
Thanks, I appreciate the assistance!

I'm able to upload new watch faces, no issue. I see them update on the Fossil within seconds.

Here's a copy of my watch face and menu companion config: [jefferderp.zip](https://github.com/dakhnod/Fossil-HR-Menu-Companion/files/14465640/jefferderp.zip)

I've tried with the default menu companion configuration, so I don't think the issue is with the menu being too big.

**Comment by dakhnod** [comment]
Concerning the reset: did you manage to factory reset the watch once? So that all the settings and watchfaces are reset? You should be able to do that through GB / debug / factory reset

**Comment by dakhnod** [comment]
In the watchface designer in GB, can you see the bottom line with the stored config JSON?

![Screenshot_20240305-152052](https://github.com/dakhnod/Fossil-HR-Menu-Companion/assets/26143255/636c6aac-3f54-4515-b212-e98fc7c9b9a1)

**Comment by dakhnod** [comment]
Here is a working .wapp file, btw. GB does not inject the menu structure, for some reason.
[customized.wapp.txt](https://github.com/dakhnod/Fossil-HR-Menu-Companion/files/14496689/customized.wapp.txt)

**Comment by Jefferderp** [comment]
Thanks for all your help thus far.

I tried a factory reset via Gadgetbridge - this worked as expected, and the watch was completely bare of any apps or faces. I had to login with the Fossil app to retrieve a new authentication key, then uninstall Fossil and pair with Gadgetbridge, and re-load my apps.

Unfortunately the behavior is the same.

I tried the customized.wapp you sent, but the watch refuses to load it. I did rename to the correct extension. It gets pushed to the watch, but won't become active, even when I choose 'Activate' in Gadgetbridge.

However, my original 'One.wapp' watch face works just fine.

Something very interesting is that my watch face creation screen does *not* show the menu JSON structure like yours does. I tried resetting the Menu Companion app, but it made no difference.

Here's a screenshot:

![image](https://github.com/dakhnod/Fossil-HR-Menu-Companion/assets/13530594/6f29155f-2d58-421c-a560-4f2ef0708ae6)

**Comment by dakhnod** [comment]
When you send the Menü structure from the companion, there should be two Things:

1. A snackbar saying "sending Menu structure to GB"
2. A Toast saying "Menu structure Set in GB" or Something

Can you confirm?

**Comment by Jefferderp** [comment]
Oh my god, I feel like an idiot...hahahaha.

It works!!!

I had no idea I was supposed to tap the FAB in Menu Companion. Because the icon is an envelope, I assumed this was for sending an email for a bug report, feature request, etc.

I propose changing the icon to something else, like one of these:

![baseline_autorenew_white_24dp](https://github.com/dakhnod/Fossil-HR-Menu-Companion/assets/13530594/02870587-7381-4d29-ace4-acd685e18969)
![baseline_done_white_24dp](https://github.com/dakhnod/Fossil-HR-Menu-Companion/assets/13530594/a2e26770-482c-4e16-8b93-e199d3c359c5)
![baseline_visibility_white_24dp](https://github.com/dakhnod/Fossil-HR-Menu-Companion/assets/13530594/7d2dcaf5-314d-4384-b1f8-3e7c95c1ddb8)

Has this button always been a requirement? I could swear that in the past, the menu was retrieved automatically.

In any case, this issue is resolved now. Thanks very much for your assistance.

**Comment by dakhnod** [comment]
I wish you tried that FAB to send a bug report instead of opening an issue...

Jokes aside, here's what happened:

Since the menu was not persistet on the watch, a mechanism was implemented where the watchface fetches the newest menu from the Menu companion through GB on start. This is probably what did it for you.  

For "several months" now, this mechanism is gone, and it stopped working for you...

I agree that the FAB is very unintuitive rn, will change the icon.

**Comment by Jefferderp** [comment]
I wish I had tried it too :) I outsmarted myself!

So I did remember correctly, there was a time when the menu was loaded automatically. I must have updated Gadgetbridge, and the behavior changed without me realizing.

Thanks again very much for your troubleshooting. Ironic that the issue was something so simple.

**Comment by dakhnod** [comment]
Good reminder to Change the Icon. Didn't think anyone used the companion...

**Comment by Jefferderp** [comment]
I love it, personally. I'm a hacker at heart, and I love being able to construct a custom menu. Ad being able to send intents back to the phone to be received by Tasker is a huge plus. Thanks again for developing it!

**Comment by dakhnod** [comment]
I'm pretty proud of how powerful it is...once you understand how to use. Not too intuitive, I admit

**Comment by Jefferderp** [comment]
Good enough for me :)

I forgot you also developed Better Stopwatch and Watch Authenticator. I use these tools regularly, so thank you again for all your work.

You should add some screenshots and descriptions in these repos! They're great work, and worthy of showing off.

Do you accept donations, by the way?

**Comment by dakhnod** [comment]
Great you find use for those! If you want to support me, you could send something via PayPal to dakhnod@gmail.com . Just know that you can expect my support without donations as well, as long as I can find some time :)

**Comment by Jefferderp** [comment]
Much appreciated!
