### ISSUE TITLE
Unable to install v1.1.0 on Android 11 (LineageOS 18.1)

### ISSUE THREAD

**Issue by hkramski** [dakhnod/Fossil-HR-Menu-Companion#4]
I am unable to install the .apk on my phone (Aquaris X Pro, Android 11, LineageOS 18.1). Installation simply aborts with "App not installed". SHA256 checksum is bc91856d968f8ec6940de30543ebc53d7e8fecaed4869523a30058a24981efd9 which matches the download on my desktop pc.

**Comment by dakhnod** [comment]
Could you try installing via adb? That might give a clearer message...

**Comment by hkramski** [comment]
Looks like the -t switch was needed, thank you!
```
$ adb install HR-Menu-Companion-1.1.0-app-debug.apk 
Performing Streamed Install
adb: failed to install HR-Menu-Companion-1.1.0-app-debug.apk: Failure [INSTALL_FAILED_TEST_ONLY: installPackageLI]
$ adb install -t HR-Menu-Companion-1.1.0-app-debug.apk
Performing Streamed Install
Success
```
