### ISSUE TITLE
APK cannot be installed

### ISSUE THREAD

**Issue by MortenHannemose** [dakhnod/Fossil-HR-Menu-Companion#5]
I cannot install the APK from https://github.com/dakhnod/Fossil-HR-Menu-Companion/releases/tag/v1.1.0 on my phone.
The error is "App not installed as package appears to be invalid".

When I clone the repository and compile it with a clean install of Android Studio it installs and works without problems. 
I'm running Android 12.

**Comment by dakhnod** [comment]
Okay, I'll check it out.

**Comment by dakhnod** [comment]
@MortenHannemose could you please try again?

**Comment by MortenHannemose** [comment]
Thanks, APK works on my phone.
