### ISSUE TITLE
Import functionality is missing

### ISSUE THREAD

**Issue by arjan-s** [dakhnod/Fossil-HR-Menu-Companion#6]
At the moment, the import configuration function is missing in the app. The configuration can be exported (backed up) but not imported afterwards. Could you please add this functionality? It would make development and testing a lot easier, as I rely on the custom menu for my day to day usage. :)

**Comment by dakhnod** [comment]
Could you please test the latest version? Import might work...

**Comment by arjan-s** [comment]
Works like a charm! Thank you!
Could you please make a release too? :)

**Comment by dakhnod** [comment]
done.
